---
repos:
  - repo: local
    hooks:
      - id: format
        name: format code
        entry: nix fmt
        language: system
        always_run: true
        pass_filenames: false
      - id: eval
        name: check configuration evaluates
        entry: bash ./bin/home-instanciate.sh
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - push
