name: Build
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - bin
      - .pre-commit-config.yaml
      - README.md
      - LICENSE
  push:
    branches:
      - main
    paths-ignore:
      - bin
      - .pre-commit-config.yaml
      - README.md
      - LICENSE
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: df -h
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-docker-images: 'true'
      - run: df -h
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: mindriot101-home
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build '.#homeConfigurations.x86_64-linux.simon.activationPackage'

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: mindriot101-home
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build '.#homeConfigurations.x86_64-darwin.simon.activationPackage'
