name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - bin
      - .pre-commit-config.yaml
      - README.md
      - LICENSE
  push:
    branches:
      - main
    paths-ignore:
      - bin
      - .pre-commit-config.yaml
      - README.md
      - LICENSE
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: mindriot101-home
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build '.#homeConfigurations.x86_64-linux.simon.activationPackage'

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: mindriot101-home
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build '.#homeConfigurations.x86_64-darwin.simon.activationPackage'
